# Generated by Django 2.2.3 on 2019-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(choices=[(True, 'man'), (False, 'woman')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='sampleblog/images'),
        ),
    ]
