# Generated by Django 2.2.3 on 2019-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0002_auto_20190720_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'man'), (False, 'woman')], null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sampleblog/images', verbose_name='ユーザー画像'),
        ),
    ]
